'blank_issues_enabled': true
'contact_links':
  - 'about': >
        Please check TrustTunnel console client README for more useful information about our product
    'name': 'README'
    'url': 'https://github.com/TrustTunnel/TrustTunnelClient/blob/master/README.md'
